### ISSUE TITLE
Rails 7.0 support

### ISSUE THREAD

**Issue by yahonda** [pingcap/activerecord-tidb-adapter#33]
Rails 7.0.0 has been released on Dec 15, 2020 https://rubyonrails.org/2021/12/15/Rails-7-fulfilling-a-vision , Active Record TiDB adapter needs to release `activerecord-tidb-adapter 7.0.0`.

## Tasks needed

- [x] Create `7-0-stable` from the latest master branch

- [x] Update Gemfile and other information to support Rails 7.0.0 or higher at `7-0-stable` branch
https://github.com/pingcap/activerecord-tidb-adapter/blob/deca938ba260fedf650099e1716da56575df5f1a/activerecord-tidb-adapter.gemspec#L32 via #34
- [x] Update Gemfile at the new master branch to support Rails 7.1.0.alpha
via https://github.com/pingcap/activerecord-tidb-adapter/pull/36

- [x] Rails 7.0.1 or higher is required https://github.com/pingcap/activerecord-tidb-adapter/pull/45

**Comment by yahonda** [comment]
@hooopo Would you take care of `Create 7-0-stable from the latest master branch`? because my account does not have privileges to push a new branch at https://github.com/pingcap/activerecord-tidb-adapter . Once the `7-0-stable` branch has been made I can open some pull requests.

**Comment by hooopo** [comment]
> @hooopo Would you take care of `Create 7-0-stable from the latest master branch`? because my account does not have privileges to push a new branch at https://github.com/pingcap/activerecord-tidb-adapter . Once the `7-0-stable` branch has been made I can open some pull requests.

done

**Comment by yahonda** [comment]
Changed the subject name to `Rails 7.0 support ` because it requires Rails 7.0.1. refer to https://github.com/pingcap/activerecord-tidb-adapter/pull/45 for the background.

**Comment by yahonda** [comment]
@hooopo Would you release `activerecord-tidb-adapter` 7.0.0 from the `7-0-stable` branch and push it to the https://rubygems.org/gems/activerecord-tidb-adapter ?

**Comment by hooopo** [comment]
@yahonda released

**Comment by yahonda** [comment]
Thanks!

**Comment by yahonda** [comment]
Just updated release section for v7.0.0

https://github.com/pingcap/activerecord-tidb-adapter/releases/tag/v7.0.0
